#!/usr/bin/env python3

import sys
import os 

from analyzer import Analyzer
from nltk.tokenize import TweetTokenizer
from helpers import get_user_timeline
from termcolor import colored

def main():
    # absolute paths to lists
    # taken from smile.py
    
    if len(sys.argv) != 2:
        print("Usage: ./tweets @screen_name")
        exit(0)
    
    user = sys.argv[1].strip('@')
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    
    tokenize = TweetTokenizer().tokenize
    
    user_timeline = get_user_timeline(user, 50)
    
    if user_timeline is None:
        exit("Could not find user, please try a different @ name!")
        
    for tweet in user_timeline:
        score = 0
        for word in tokenize(tweet):
            score += analyzer.analyze(word)
        if score < 0: 
            print(colored(str(score) + " " + tweet, "red"))
        elif score > 0:
            print(colored(str(score) + " " + tweet, "green"))
        else:
            print(colored(str(score) + " " + tweet, "yellow"))
            
if __name__ == "__main__":
    main()